import type {
  TahawiyyahCurriculum,
  TahawiyyahSourceUnit,
} from './tahawiyyah-curriculum-types'

import sourceUnits from './tahawiyyah-source-units.json'
import englishSource from './tahawiyyah-english-source.json'

const units = sourceUnits as Array<{
  sourceParagraph: number
  arabic: string
}>

export const TAHAWIYYAH_SOURCE_UNITS: TahawiyyahSourceUnit[] =
  units.map((unit) => ({
    id: unit.sourceParagraph,
    arabic: unit.arabic,
  }))

export const TAHAWIYYAH_ENGLISH_SOURCE = englishSource as Array<{
  sourceParagraph: number
  text: string
}>

export const TAHAWIYYAH_CURRICULUM: TahawiyyahCurriculum = {
  source: {
    id: 'al-aqidah-al-tahawiyyah',
    titleArabic: 'العقيدة الطحاوية',
    titleEnglish: 'Al-Aqidah al-Tahawiyyah',
    authorArabic: 'أبو جعفر أحمد بن محمد الطحاوي',
    authorEnglish: 'Abu Ja‘far Ahmad ibn Muhammad al-Tahawi',
    sourceUrl: 'https://islamhouse.com/ar/books/1899',
  },
  lessons: [
    {
      number: 1,
      slug: 'tawhid-and-the-uniqueness-of-allah',
      teachingTitle: 'Tawhid and the uniqueness of Allah',
      sourceUnitIds: [1,2,3,4,5,6,7,8,9,10,11],
      original: { language: 'ar', sourceUnitIds: [1,2,3,4,5,6,7,8,9,10,11] },
      title: { en: 'Tawhid and the uniqueness of Allah', sw: 'Tawhidi na upekee wa Allah', fr: 'Le Tawhid et l’unicité d’Allah' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 2,
      slug: 'allahs-attributes-lordship-creation-and-power',
      teachingTitle: 'Allah’s attributes, lordship, creation, and power',
      sourceUnitIds: [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26],
      original: { language: 'ar', sourceUnitIds: [12,13,14,15,16,17,18,19,20,21,22,23,24,25,26] },
      title: { en: 'Allah’s attributes, lordship, creation, and power', sw: 'Sifa, Uola, uumbaji na uwezo wa Allah', fr: 'Les attributs, la seigneurie, la création et la puissance d’Allah' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 3,
      slug: 'allahs-knowledge-decree-will-and-wisdom',
      teachingTitle: 'Allah’s knowledge, decree, will, and wisdom',
      sourceUnitIds: [27,28,29,30,31,32,33,34],
      original: { language: 'ar', sourceUnitIds: [27,28,29,30,31,32,33,34] },
      title: { en: 'Allah’s knowledge, decree, will, and wisdom', sw: 'Elimu, Qadar, matakwa na hikima ya Allah', fr: 'La connaissance, le décret, la volonté et la sagesse d’Allah' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 4,
      slug: 'muhammad-the-messenger-and-final-prophet',
      teachingTitle: 'Muhammad ﷺ: the Messenger and final Prophet',
      sourceUnitIds: [35,36,37],
      original: { language: 'ar', sourceUnitIds: [35,36,37] },
      title: { en: 'Muhammad ﷺ: the Messenger and final Prophet', sw: 'Muhammad ﷺ: Mtume na Nabii wa mwisho', fr: 'Muhammad ﷺ : le Messager et dernier Prophète' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 5,
      slug: 'the-quran-as-the-speech-of-allah',
      teachingTitle: 'The Quran as the speech of Allah',
      sourceUnitIds: [38,39,40,41],
      original: { language: 'ar', sourceUnitIds: [38,39,40,41] },
      title: { en: 'The Quran as the speech of Allah', sw: 'Qurani kama maneno ya Allah', fr: 'Le Coran comme parole d’Allah' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 6,
      slug: 'seeing-allah-and-affirming-his-transcendence',
      teachingTitle: 'Seeing Allah and affirming His transcendence',
      sourceUnitIds: [42,43,44,45,46,47],
      original: { language: 'ar', sourceUnitIds: [42,43,44,45,46,47] },
      title: { en: 'Seeing Allah and affirming His transcendence', sw: 'Kumuona Allah na kuthibitisha utukufu Wake', fr: 'Voir Allah et affirmer Sa transcendance' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 7,
      slug: 'the-miraj-the-hawd-intercession-and-the-covenant',
      teachingTitle: 'The Mi‘raj, the Hawd, intercession, and the covenant',
      sourceUnitIds: [48,49,50,51],
      original: { language: 'ar', sourceUnitIds: [48,49,50,51] },
      title: { en: 'The Mi‘raj, the Hawd, intercession, and the covenant', sw: 'Mi’raj, Hawd, uombezi na agano', fr: 'Le Mi‘raj, le Hawd, l’intercession et l’alliance' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 8,
      slug: 'divine-decree-and-the-limits-of-human-knowledge',
      teachingTitle: 'Divine decree and the limits of human knowledge',
      sourceUnitIds: [52,53,54,55,56,57,58,59,60],
      original: { language: 'ar', sourceUnitIds: [52,53,54,55,56,57,58,59,60] },
      title: { en: 'Divine decree and the limits of human knowledge', sw: 'Qadar ya Allah na mipaka ya elimu ya mwanadamu', fr: 'Le décret divin et les limites de la connaissance humaine' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 9,
      slug: 'the-throne-the-kursi-ibrahim-musa-and-the-prophets',
      teachingTitle: 'The Throne, the Kursi, Ibrahim, Musa, and the Prophets',
      sourceUnitIds: [61,62,63],
      original: { language: 'ar', sourceUnitIds: [61,62,63] },
      title: { en: 'The Throne, the Kursi, Ibrahim, Musa, and the Prophets', sw: 'Arshi, Kursi, Ibrahim, Musa na Manabii', fr: 'Le Trône, le Kursi, Ibrahim, Musa et les Prophètes' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 10,
      slug: 'the-muslim-believer-the-quran-and-conduct-of-faith',
      teachingTitle: 'The Muslim believer, the Quran, and conduct of faith',
      sourceUnitIds: [64,65,66,67,68,69,70],
      original: { language: 'ar', sourceUnitIds: [64,65,66,67,68,69,70] },
      title: { en: 'The Muslim believer, the Quran, and conduct of faith', sw: 'Muumini Muislamu, Qurani na mwenendo wa imani', fr: 'Le croyant musulman, le Coran et la conduite de la foi' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 11,
      slug: 'the-nature-and-pillars-of-faith',
      teachingTitle: 'The nature and pillars of faith',
      sourceUnitIds: [71,72,73,74,75],
      original: { language: 'ar', sourceUnitIds: [71,72,73,74,75] },
      title: { en: 'The nature and pillars of faith', sw: 'Asili na nguzo za imani', fr: 'La nature et les piliers de la foi' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 12,
      slug: 'the-definition-and-equality-of-faith',
      teachingTitle: 'The definition and equality of faith',
      sourceUnitIds: [76,77],
      original: { language: 'ar', sourceUnitIds: [76,77] },
      title: { en: 'The definition and equality of faith', sw: 'Maana na usawa wa imani', fr: 'La définition et l’égalité de la foi' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 13,
      slug: 'the-muslim-community-leadership-and-the-sunnah',
      teachingTitle: 'The Muslim community, leadership, and the Sunnah',
      sourceUnitIds: [78,79,80,81,82],
      original: { language: 'ar', sourceUnitIds: [78,79,80,81,82] },
      title: { en: 'The Muslim community, leadership, and the Sunnah', sw: 'Jumuiya ya Waislamu, uongozi na Sunnah', fr: 'La communauté musulmane, le leadership et la Sunnah' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 14,
      slug: 'selected-practical-matters',
      teachingTitle: 'Selected practical matters: wiping over footwear, Hajj, and Jihad',
      sourceUnitIds: [83,84],
      original: { language: 'ar', sourceUnitIds: [83,84] },
      title: { en: 'Selected practical matters: wiping over footwear, Hajj, and Jihad', sw: 'Masuala ya vitendo: kupangusa juu ya viatu, Hija na Jihadi', fr: 'Questions pratiques : essuyage des chaussures, Hajj et Jihad' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 15,
      slug: 'angels-and-the-life-of-the-grave',
      teachingTitle: 'Angels and the life of the grave',
      sourceUnitIds: [85,86,87,88,89],
      original: { language: 'ar', sourceUnitIds: [85,86,87,88,89] },
      title: { en: 'Angels and the life of the grave', sw: 'Malaika na maisha ya kaburini', fr: 'Les anges et la vie de la tombe' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 16,
      slug: 'the-resurrection-judgment-paradise-and-hell',
      teachingTitle: 'The Resurrection, Judgment, Paradise, and Hell',
      sourceUnitIds: [90,91,92,93],
      original: { language: 'ar', sourceUnitIds: [90,91,92,93] },
      title: { en: 'The Resurrection, Judgment, Paradise, and Hell', sw: 'Kufufuliwa, Hukumu, Pepo na Jahannam', fr: 'La Résurrection, le Jugement, le Paradis et l’Enfer' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 17,
      slug: 'human-actions-ability-divine-will-and-responsibility',
      teachingTitle: 'Human actions, ability, divine will, and responsibility',
      sourceUnitIds: [94,95,96,97,98],
      original: { language: 'ar', sourceUnitIds: [94,95,96,97,98] },
      title: { en: 'Human actions, ability, divine will, and responsibility', sw: 'Matendo ya mwanadamu, uwezo, matakwa ya Allah na uwajibikaji', fr: 'Les actes humains, la capacité, la volonté divine et la responsabilité' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 18,
      slug: 'supplication-benefit-for-the-dead-and-divine-attributes',
      teachingTitle: 'Supplication, benefit for the dead, and divine attributes',
      sourceUnitIds: [99,100,101],
      original: { language: 'ar', sourceUnitIds: [99,100,101] },
      title: { en: 'Supplication, benefit for the dead, and divine attributes', sw: 'Dua, manufaa kwa waliokufa na sifa za Allah', fr: 'Invocation, bénéfice pour les morts et attributs divins' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 19,
      slug: 'the-companions-ahl-al-bayt-scholars-and-righteous-people',
      teachingTitle: 'The Companions, Ahl al-Bayt, scholars, and righteous people',
      sourceUnitIds: [102,103,104,105,106,107,108],
      original: { language: 'ar', sourceUnitIds: [102,103,104,105,106,107,108] },
      title: { en: 'The Companions, Ahl al-Bayt, scholars, and righteous people', sw: 'Maswahaba, Ahl al-Bayt, wanazuoni na watu wema', fr: 'Les Compagnons, Ahl al-Bayt, les savants et les pieux' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
    {
      number: 20,
      slug: 'signs-of-the-hour-unity-and-the-conclusion-of-the-creed',
      teachingTitle: 'Signs of the Hour, unity, and the conclusion of the creed',
      sourceUnitIds: [109,110,111,112,113,114],
      original: { language: 'ar', sourceUnitIds: [109,110,111,112,113,114] },
      title: { en: 'Signs of the Hour, unity, and the conclusion of the creed', sw: 'Alama za Kiyama, umoja na hitimisho la aqida', fr: 'Les signes de l’Heure, l’unité et la conclusion de la croyance' },
      translations: [], explanation: { en: '', sw: '', fr: '' },
      quranReferences: [], hadithReferences: [], scholarlyReferences: [],
    },
  ],
}
